# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
# Uncomment this line if you're using Swift
# use_frameworks!



target 'TheMostBeautiful' do
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

    pod 'TOPageView'
    pod 'SDWebImage'
    pod 'TONetworking'
    pod 'MBProgressHUD'
    pod 'MessageThrottle'
    pod 'MJRefresh'
    pod 'MJExtension'

    pod 'iCarousel'
    pod 'Masonry'
    pod 'MBProgressHUD'
    pod 'ReactiveObjC'
#    pod 'DDLogger'
    pod 'TouchJSON'
end
